name: cubes-and-clouds
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - geopandas
  - rasterio
  - xarray
  - rioxarray
  - openeo
  - sentinelhub
  - leafmap
  - shapely
  - h5netcdf
  - netcdf4
  - pystac
  - scikit-learn
  - pip
  - pip:
    - rio-stac
    - jupyter-book
    - sphinx-exercise
    - rio_stac
    - scikit-learn
    - openeo-processes-dask[implementations]
    - openeo-pg-parser-networkx
